// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Context;

namespace StarWars.Migrations
{
    [DbContext(typeof(StarWarsDbContext))]
    [Migration("20191025220237_StarsShip")]
    partial class StarsShip
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarWars.Context.Models.StarsShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CargoCapacity")
                        .HasColumnType("bigint");

                    b.Property<string>("Consumables")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CostInCredits")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<long>("Crew")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<double>("HyperdriveRating")
                        .HasColumnType("float");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Max_atmosphering_speed")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passengers")
                        .HasColumnType("int");

                    b.Property<string>("Starship_class")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StarShips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoCapacity = 250000000L,
                            Consumables = "6 years",
                            CostInCredits = 1143350000L,
                            Created = new DateTime(2014, 12, 15, 12, 31, 42, 547, DateTimeKind.Utc),
                            Crew = 279144L,
                            Edited = new DateTime(2017, 4, 19, 10, 56, 6, 685, DateTimeKind.Utc).AddTicks(5920),
                            HyperdriveRating = 0.0,
                            Length = 19000L,
                            Manufacturer = "Kuat Drive Yards, Fondor Shipyards",
                            Max_atmosphering_speed = 0,
                            Model = "Executor-class star dreadnought",
                            Name = "Executor",
                            Passengers = 38000,
                            Starship_class = "Star dreadnought"
                        },
                        new
                        {
                            Id = 2,
                            CargoCapacity = 180000L,
                            Consumables = "1 month",
                            CostInCredits = 240000L,
                            Created = new DateTime(2014, 12, 10, 15, 48, 0, 586, DateTimeKind.Utc),
                            Crew = 5L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 431, DateTimeKind.Utc).AddTicks(4070),
                            HyperdriveRating = 0.0,
                            Length = 38L,
                            Manufacturer = "Sienar Fleet Systems, Cyngus Spaceworks",
                            Max_atmosphering_speed = 1000,
                            Model = "Sentinel-class landing craft",
                            Name = "Sentinel-class landing craft",
                            Passengers = 75,
                            Starship_class = "landing craft"
                        },
                        new
                        {
                            Id = 3,
                            CargoCapacity = 1000000000000L,
                            Consumables = "3 years",
                            CostInCredits = 1000000000000L,
                            Created = new DateTime(2014, 12, 10, 16, 36, 50, 509, DateTimeKind.Utc),
                            Crew = 342953L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 452, DateTimeKind.Utc).AddTicks(5890),
                            HyperdriveRating = 0.0,
                            Length = 120000L,
                            Manufacturer = "Imperial Department of Military Research, Sienar Fleet Systems",
                            Max_atmosphering_speed = 0,
                            Model = "DS-1 Orbital Battle Station",
                            Name = "Death Star",
                            Passengers = 843342,
                            Starship_class = "Deep Space Mobile Battlestation"
                        },
                        new
                        {
                            Id = 4,
                            CargoCapacity = 100000L,
                            Consumables = "2 months",
                            CostInCredits = 100000L,
                            Created = new DateTime(2014, 12, 10, 16, 59, 45, 94, DateTimeKind.Utc),
                            Crew = 4L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 464, DateTimeKind.Utc).AddTicks(1560),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Corellian Engineering Corporation",
                            Max_atmosphering_speed = 1050,
                            Model = "YT-1300 light freighter",
                            Name = "Millennium Falcon",
                            Passengers = 6,
                            Starship_class = "Light freighter"
                        },
                        new
                        {
                            Id = 5,
                            CargoCapacity = 110L,
                            Consumables = "1 week",
                            CostInCredits = 134999L,
                            Created = new DateTime(2014, 12, 12, 11, 0, 39, 817, DateTimeKind.Utc),
                            Crew = 2L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 479, DateTimeKind.Utc).AddTicks(7060),
                            HyperdriveRating = 0.0,
                            Length = 14L,
                            Manufacturer = "Koensayr Manufacturing",
                            Max_atmosphering_speed = 0,
                            Model = "BTL Y-wing",
                            Name = "Y-wing",
                            Passengers = 0,
                            Starship_class = "assault starfighter"
                        },
                        new
                        {
                            Id = 6,
                            CargoCapacity = 110L,
                            Consumables = "1 week",
                            CostInCredits = 149999L,
                            Created = new DateTime(2014, 12, 12, 11, 19, 5, 340, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 491, DateTimeKind.Utc).AddTicks(2330),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Incom Corporation",
                            Max_atmosphering_speed = 1050,
                            Model = "T-65 X-wing",
                            Name = "X-wing",
                            Passengers = 0,
                            Starship_class = "Starfighter"
                        },
                        new
                        {
                            Id = 7,
                            CargoCapacity = 150L,
                            Consumables = "5 days",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 12, 11, 21, 32, 991, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 549, DateTimeKind.Utc).AddTicks(470),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Sienar Fleet Systems",
                            Max_atmosphering_speed = 1200,
                            Model = "Twin Ion Engine Advanced x1",
                            Name = "TIE Advanced x1",
                            Passengers = 0,
                            Starship_class = "Starfighter"
                        },
                        new
                        {
                            Id = 8,
                            CargoCapacity = 70000L,
                            Consumables = "1 month",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 15, 13, 0, 56, 332, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 716, DateTimeKind.Utc).AddTicks(2730),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Kuat Systems Engineering",
                            Max_atmosphering_speed = 1000,
                            Model = "Firespray-31-class patrol and attack",
                            Name = "Slave 1",
                            Passengers = 6,
                            Starship_class = "Patrol craft"
                        },
                        new
                        {
                            Id = 9,
                            CargoCapacity = 80000L,
                            Consumables = "2 months",
                            CostInCredits = 240000L,
                            Created = new DateTime(2014, 12, 15, 13, 4, 47, 235, DateTimeKind.Utc),
                            Crew = 6L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 795, DateTimeKind.Utc).AddTicks(4050),
                            HyperdriveRating = 0.0,
                            Length = 20L,
                            Manufacturer = "Sienar Fleet Systems",
                            Max_atmosphering_speed = 850,
                            Model = "Lambda-class T-4a shuttle",
                            Name = "Imperial shuttle",
                            Passengers = 20,
                            Starship_class = "Armed government transport"
                        },
                        new
                        {
                            Id = 10,
                            CargoCapacity = 6000000L,
                            Consumables = "2 years",
                            CostInCredits = 8500000L,
                            Created = new DateTime(2014, 12, 15, 13, 6, 30, 813, DateTimeKind.Utc),
                            Crew = 854L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 848, DateTimeKind.Utc).AddTicks(3290),
                            HyperdriveRating = 0.0,
                            Length = 300L,
                            Manufacturer = "Kuat Drive Yards",
                            Max_atmosphering_speed = 800,
                            Model = "EF76 Nebulon-B escort frigate",
                            Name = "EF76 Nebulon-B escort frigate",
                            Passengers = 75,
                            Starship_class = "Escort ship"
                        },
                        new
                        {
                            Id = 11,
                            CargoCapacity = 0L,
                            Consumables = "2 years",
                            CostInCredits = 104000000L,
                            Created = new DateTime(2014, 12, 18, 10, 54, 57, 804, DateTimeKind.Utc),
                            Crew = 5400L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 957, DateTimeKind.Utc).AddTicks(8520),
                            HyperdriveRating = 0.0,
                            Length = 1200L,
                            Manufacturer = "Mon Calamari shipyards",
                            Max_atmosphering_speed = 0,
                            Model = "MC80 Liberty type Star Cruiser",
                            Name = "Calamari Cruiser",
                            Passengers = 1200,
                            Starship_class = "Star Cruiser"
                        },
                        new
                        {
                            Id = 12,
                            CargoCapacity = 40L,
                            Consumables = "1 week",
                            CostInCredits = 175000L,
                            Created = new DateTime(2014, 12, 18, 11, 16, 34, 542, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 978, DateTimeKind.Utc).AddTicks(7540),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Alliance Underground Engineering, Incom Corporation",
                            Max_atmosphering_speed = 1300,
                            Model = "RZ-1 A-wing Interceptor",
                            Name = "A-wing",
                            Passengers = 0,
                            Starship_class = "Starfighter"
                        },
                        new
                        {
                            Id = 13,
                            CargoCapacity = 45L,
                            Consumables = "1 week",
                            CostInCredits = 220000L,
                            Created = new DateTime(2014, 12, 18, 11, 18, 4, 763, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 11, DateTimeKind.Utc).AddTicks(1930),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Slayn & Korpil",
                            Max_atmosphering_speed = 950,
                            Model = "A/SF-01 B-wing starfighter",
                            Name = "B-wing",
                            Passengers = 0,
                            Starship_class = "Assault Starfighter"
                        },
                        new
                        {
                            Id = 14,
                            CargoCapacity = 0L,
                            Consumables = "unknown",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 19, 17, 1, 31, 488, DateTimeKind.Utc),
                            Crew = 9L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 27, DateTimeKind.Utc).AddTicks(3080),
                            HyperdriveRating = 0.0,
                            Length = 115L,
                            Manufacturer = "Corellian Engineering Corporation",
                            Max_atmosphering_speed = 900,
                            Model = "Consular-class cruiser",
                            Name = "Republic Cruiser",
                            Passengers = 16,
                            Starship_class = "Space cruiser"
                        },
                        new
                        {
                            Id = 15,
                            CargoCapacity = 65L,
                            Consumables = "7 days",
                            CostInCredits = 200000L,
                            Created = new DateTime(2014, 12, 19, 17, 39, 17, 582, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 79, DateTimeKind.Utc).AddTicks(4520),
                            HyperdriveRating = 0.0,
                            Length = 11L,
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps",
                            Max_atmosphering_speed = 1100,
                            Model = "N-1 starfighter",
                            Name = "Naboo fighter",
                            Passengers = 0,
                            Starship_class = "Starfighter"
                        },
                        new
                        {
                            Id = 16,
                            CargoCapacity = 0L,
                            Consumables = "unknown",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 19, 17, 45, 3, 506, DateTimeKind.Utc),
                            Crew = 8L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 91, DateTimeKind.Utc).AddTicks(9250),
                            HyperdriveRating = 0.0,
                            Length = 76L,
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
                            Max_atmosphering_speed = 920,
                            Model = "J-type 327 Nubian royal starship",
                            Name = "Naboo Royal Starship",
                            Passengers = 0,
                            Starship_class = "yacht"
                        },
                        new
                        {
                            Id = 17,
                            CargoCapacity = 2500000L,
                            Consumables = "30 days",
                            CostInCredits = 55000000L,
                            Created = new DateTime(2014, 12, 20, 9, 39, 56, 116, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 105, DateTimeKind.Utc).AddTicks(5220),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Republic Sienar Systems",
                            Max_atmosphering_speed = 1180,
                            Model = "Star Courier",
                            Name = "Scimitar",
                            Passengers = 6,
                            Starship_class = "Space Transport"
                        },
                        new
                        {
                            Id = 18,
                            CargoCapacity = 0L,
                            Consumables = "1 year",
                            CostInCredits = 2000000L,
                            Created = new DateTime(2014, 12, 20, 11, 5, 51, 237, DateTimeKind.Utc),
                            Crew = 5L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 124, DateTimeKind.Utc).AddTicks(3860),
                            HyperdriveRating = 0.0,
                            Length = 39L,
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
                            Max_atmosphering_speed = 2000,
                            Model = "J-type diplomatic barge",
                            Name = "J-type diplomatic barge",
                            Passengers = 10,
                            Starship_class = "Diplomatic barge"
                        },
                        new
                        {
                            Id = 19,
                            CargoCapacity = 0L,
                            Consumables = "unknown",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 20, 17, 24, 23, 509, DateTimeKind.Utc),
                            Crew = 0L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 135, DateTimeKind.Utc).AddTicks(9870),
                            HyperdriveRating = 0.0,
                            Length = 390L,
                            Manufacturer = "Botajef Shipyards",
                            Max_atmosphering_speed = 0,
                            Model = "Botajef AA-9 Freighter-Liner",
                            Name = "AA-9 Coruscant freighter",
                            Passengers = 30000,
                            Starship_class = "freighter"
                        },
                        new
                        {
                            Id = 20,
                            CargoCapacity = 60L,
                            Consumables = "7 days",
                            CostInCredits = 180000L,
                            Created = new DateTime(2014, 12, 20, 17, 35, 23, 906, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 147, DateTimeKind.Utc).AddTicks(7460),
                            HyperdriveRating = 0.0,
                            Length = 8L,
                            Manufacturer = "Kuat Systems Engineering",
                            Max_atmosphering_speed = 1150,
                            Model = "Delta-7 Aethersprite-class interceptor",
                            Name = "Jedi starfighter",
                            Passengers = 0,
                            Starship_class = "Starfighter"
                        },
                        new
                        {
                            Id = 21,
                            CargoCapacity = 0L,
                            Consumables = "unknown",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 20, 17, 46, 46, 847, DateTimeKind.Utc),
                            Crew = 4L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 158, DateTimeKind.Utc).AddTicks(9690),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps",
                            Max_atmosphering_speed = 8000,
                            Model = "H-type Nubian yacht",
                            Name = "H-type Nubian yacht",
                            Passengers = 0,
                            Starship_class = "yacht"
                        },
                        new
                        {
                            Id = 22,
                            CargoCapacity = 36000000L,
                            Consumables = "2 years",
                            CostInCredits = 150000000L,
                            Created = new DateTime(2014, 12, 10, 15, 8, 19, 848, DateTimeKind.Utc),
                            Crew = 47060L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 410, DateTimeKind.Utc).AddTicks(9410),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Kuat Drive Yards",
                            Max_atmosphering_speed = 975,
                            Model = "Imperial I-class Star Destroyer",
                            Name = "Star Destroyer",
                            Passengers = 0,
                            Starship_class = "Star Destroyer"
                        },
                        new
                        {
                            Id = 23,
                            CargoCapacity = 50000000L,
                            Consumables = "4 years",
                            CostInCredits = 125000000L,
                            Created = new DateTime(2014, 12, 20, 19, 40, 21, 902, DateTimeKind.Utc),
                            Crew = 600L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 195, DateTimeKind.Utc).AddTicks(1650),
                            HyperdriveRating = 0.0,
                            Length = 1088L,
                            Manufacturer = "Rendili StarDrive, Free Dac Volunteers Engineering corps.",
                            Max_atmosphering_speed = 1050,
                            Model = "Providence-class carrier/destroyer",
                            Name = "Trade Federation cruiser",
                            Passengers = 48247,
                            Starship_class = "capital ship"
                        },
                        new
                        {
                            Id = 24,
                            CargoCapacity = 50000L,
                            Consumables = "56 days",
                            CostInCredits = 1000000L,
                            Created = new DateTime(2014, 12, 20, 19, 48, 40, 409, DateTimeKind.Utc),
                            Crew = 5L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 208, DateTimeKind.Utc).AddTicks(5840),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Cygnus Spaceworks",
                            Max_atmosphering_speed = 2000,
                            Model = "Theta-class T-2c shuttle",
                            Name = "Theta-class T-2c shuttle",
                            Passengers = 16,
                            Starship_class = "transport"
                        },
                        new
                        {
                            Id = 25,
                            CargoCapacity = 0L,
                            Consumables = "unknown",
                            CostInCredits = 0L,
                            Created = new DateTime(2015, 4, 17, 6, 58, 50, 614, DateTimeKind.Utc).AddTicks(4750),
                            Crew = 1L,
                            Edited = new DateTime(2015, 4, 17, 6, 58, 50, 614, DateTimeKind.Utc).AddTicks(5280),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Incom",
                            Max_atmosphering_speed = 0,
                            Model = "T-70 X-wing fighter",
                            Name = "T-70 X-wing fighter",
                            Passengers = 0,
                            Starship_class = "fighter"
                        },
                        new
                        {
                            Id = 26,
                            CargoCapacity = 19000000L,
                            Consumables = "6 months",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 15, 12, 34, 52, 264, DateTimeKind.Utc),
                            Crew = 6L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 44, 680, DateTimeKind.Utc).AddTicks(8380),
                            HyperdriveRating = 0.0,
                            Length = 90L,
                            Manufacturer = "Gallofree Yards, Inc.",
                            Max_atmosphering_speed = 650,
                            Model = "GR-75 medium transport",
                            Name = "Rebel transport",
                            Passengers = 90,
                            Starship_class = "Medium transport"
                        },
                        new
                        {
                            Id = 27,
                            CargoCapacity = 4000000000L,
                            Consumables = "500 days",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 19, 17, 4, 6, 323, DateTimeKind.Utc),
                            Crew = 175L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 42, DateTimeKind.Utc).AddTicks(9000),
                            HyperdriveRating = 0.0,
                            Length = 3170L,
                            Manufacturer = "Hoersch-Kessel Drive, Inc.",
                            Max_atmosphering_speed = 0,
                            Model = "Lucrehulk-class Droid Control Ship",
                            Name = "Droid control ship",
                            Passengers = 139000,
                            Starship_class = "Droid control ship"
                        },
                        new
                        {
                            Id = 28,
                            CargoCapacity = 11250000L,
                            Consumables = "2 years",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 20, 18, 8, 42, 926, DateTimeKind.Utc),
                            Crew = 700L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 171, DateTimeKind.Utc).AddTicks(6530),
                            HyperdriveRating = 0.0,
                            Length = 752L,
                            Manufacturer = "Rothana Heavy Engineering",
                            Max_atmosphering_speed = 0,
                            Model = "Acclamator I-class assault ship",
                            Name = "Republic Assault ship",
                            Passengers = 16000,
                            Starship_class = "assault ship"
                        },
                        new
                        {
                            Id = 29,
                            CargoCapacity = 240L,
                            Consumables = "7 days",
                            CostInCredits = 35700L,
                            Created = new DateTime(2014, 12, 20, 18, 37, 56, 969, DateTimeKind.Utc),
                            Crew = 3L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 183, DateTimeKind.Utc).AddTicks(750),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Huppla Pasa Tisc Shipwrights Collective",
                            Max_atmosphering_speed = 1600,
                            Model = "Punworcca 116-class interstellar sloop",
                            Name = "Solar Sailer",
                            Passengers = 11,
                            Starship_class = "yacht"
                        },
                        new
                        {
                            Id = 30,
                            CargoCapacity = 20000000L,
                            Consumables = "2 years",
                            CostInCredits = 59000000L,
                            Created = new DateTime(2014, 12, 20, 19, 52, 56, 232, DateTimeKind.Utc),
                            Crew = 7400L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 224, DateTimeKind.Utc).AddTicks(5400),
                            HyperdriveRating = 0.0,
                            Length = 1137L,
                            Manufacturer = "Kuat Drive Yards, Allanteen Six shipyards",
                            Max_atmosphering_speed = 975,
                            Model = "Senator-class Star Destroyer",
                            Name = "Republic attack cruiser",
                            Passengers = 2000,
                            Starship_class = "star destroyer"
                        },
                        new
                        {
                            Id = 31,
                            CargoCapacity = 0L,
                            Consumables = "unknown",
                            CostInCredits = 0L,
                            Created = new DateTime(2014, 12, 20, 19, 55, 15, 396, DateTimeKind.Utc),
                            Crew = 3L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 258, DateTimeKind.Utc).AddTicks(8590),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated",
                            Max_atmosphering_speed = 1050,
                            Model = "J-type star skiff",
                            Name = "Naboo star skiff",
                            Passengers = 3,
                            Starship_class = "yacht"
                        },
                        new
                        {
                            Id = 32,
                            CargoCapacity = 60L,
                            Consumables = "2 days",
                            CostInCredits = 320000L,
                            Created = new DateTime(2014, 12, 20, 19, 56, 57, 468, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 272, DateTimeKind.Utc).AddTicks(3490),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Kuat Systems Engineering",
                            Max_atmosphering_speed = 1500,
                            Model = "Eta-2 Actis-class light interceptor",
                            Name = "Jedi Interceptor",
                            Passengers = 0,
                            Starship_class = "starfighter"
                        },
                        new
                        {
                            Id = 33,
                            CargoCapacity = 110L,
                            Consumables = "5 days",
                            CostInCredits = 155000L,
                            Created = new DateTime(2014, 12, 20, 20, 3, 48, 603, DateTimeKind.Utc),
                            Crew = 3L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 287, DateTimeKind.Utc).AddTicks(2140),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Incom Corporation, Subpro Corporation",
                            Max_atmosphering_speed = 1000,
                            Model = "Aggressive Reconnaissance-170 starfighte",
                            Name = "arc-170",
                            Passengers = 0,
                            Starship_class = "starfighter"
                        },
                        new
                        {
                            Id = 34,
                            CargoCapacity = 140L,
                            Consumables = "7 days",
                            CostInCredits = 168000L,
                            Created = new DateTime(2014, 12, 20, 20, 38, 5, 31, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 381, DateTimeKind.Utc).AddTicks(9000),
                            HyperdriveRating = 6.0,
                            Length = 0L,
                            Manufacturer = "Feethan Ottraw Scalable Assemblies",
                            Max_atmosphering_speed = 1100,
                            Model = "Belbullab-22 starfighter",
                            Name = "Belbullab-22 starfighter",
                            Passengers = 0,
                            Starship_class = "starfighter"
                        },
                        new
                        {
                            Id = 35,
                            CargoCapacity = 60L,
                            Consumables = "15 hours",
                            CostInCredits = 102500L,
                            Created = new DateTime(2014, 12, 20, 20, 43, 4, 349, DateTimeKind.Utc),
                            Crew = 1L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 396, DateTimeKind.Utc).AddTicks(7110),
                            HyperdriveRating = 0.0,
                            Length = 0L,
                            Manufacturer = "Kuat Systems Engineering",
                            Max_atmosphering_speed = 1050,
                            Model = "Alpha-3 Nimbus-class V-wing starfighter",
                            Name = "V-wing",
                            Passengers = 0,
                            Starship_class = "starfighter"
                        },
                        new
                        {
                            Id = 36,
                            CargoCapacity = 3000000L,
                            Consumables = "1 year",
                            CostInCredits = 3500000L,
                            Created = new DateTime(2014, 12, 10, 14, 20, 33, 369, DateTimeKind.Utc),
                            Crew = 165L,
                            Edited = new DateTime(2014, 12, 22, 17, 35, 45, 408, DateTimeKind.Utc).AddTicks(3680),
                            HyperdriveRating = 0.0,
                            Length = 150L,
                            Manufacturer = "Corellian Engineering Corporation",
                            Max_atmosphering_speed = 950,
                            Model = "CR90 corvette",
                            Name = "CR90 corvette",
                            Passengers = 600,
                            Starship_class = "corvette"
                        },
                        new
                        {
                            Id = 37,
                            CargoCapacity = 40000000L,
                            Consumables = "2 years",
                            CostInCredits = 57000000L,
                            Created = new DateTime(2014, 12, 20, 20, 7, 11, 538, DateTimeKind.Utc),
                            Crew = 200L,
                            Edited = new DateTime(2017, 4, 19, 10, 53, 32, 700, DateTimeKind.Utc).AddTicks(2830),
                            HyperdriveRating = 0.0,
                            Length = 825L,
                            Manufacturer = "Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries",
                            Max_atmosphering_speed = 0,
                            Model = "Munificent-class star frigate",
                            Name = "Banking clan frigate",
                            Passengers = 0,
                            Starship_class = "cruiser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
